apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: distributed-search
spec:
  selector:
    app: gateway
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
    - name: metrics
      port: 2112
      targetPort: 2112
