FROM golang:1.22-alpine AS builder
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /bin/gateway ./cmd/gateway

FROM gcr.io/distroless/static-debian12
COPY --from=builder /bin/gateway /gateway
EXPOSE 50051 2112
ENTRYPOINT ["/gateway"]
